# Generated by Django 3.2.16 on 2023-02-18 12:50

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20230218_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateField(validators=[reviews.validators.year_validator], verbose_name='Год'),
        ),
    ]
